name: Free RDP Ubuntu (LXDE Auto CRD 1H)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update & Install LXDE + Chrome + CRD
      run: |
        sudo apt update
        sudo apt install -y lxde-core lxterminal lxappearance
        sudo apt install -y wget gdebi-core

        # Install Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo gdebi -n google-chrome-stable_current_amd64.deb

        # Install Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo gdebi -n chrome-remote-desktop_current_amd64.deb

        # Buat user baru
        sudo useradd -m -s /bin/bash github
        sudo adduser github sudo
        echo 'github:rdpuser' | sudo chpasswd

        # Konfigurasi LXDE
        echo "exec startlxde" > /home/github/.xsession

        # Jalankan CRD langsung pakai tokenmu
        DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="4/0AVMBsJhX6LG0N5iy91uTa4g3x8FgZ5sSPLLS5nD09R_idrhwUr_ooyP5n3rdYXGtOPbirg" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=$(hostname)

    - name: Keep Alive (1h)
      run: |
        echo "🚀 RDP Aktif (max 1 jam)"
        sleep 1h
