name: Free RDP Ubuntu

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Xfce & Chrome Remote Desktop
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies
        sudo apt install -y wget gdebi-core

        # Install Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo gdebi -n google-chrome-stable_current_amd64.deb

        # Install Chrome Remote Desktop
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo gdebi -n chrome-remote-desktop_current_amd64.deb

        # Setup user
        sudo useradd -m -s /bin/bash github
        sudo adduser github sudo
        echo 'github:1234' | sudo chpasswd

        # Enable CRD
        echo "exec /usr/bin/xfce4-session" > /home/github/.xsession
        sudo service chrome-remote-desktop start

    - name: Keep Alive
      run: |
        echo "RDP Aktif 🚀"
        sleep 1h
        
